language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

before_install:
  - composer self-update

install:
  - composer install --no-interaction

before_script:
  - mysql -u root -e 'CREATE DATABASE testbase;'
  #- mysql -u root testbase < tests/testbase.sql

script:
  - ./vendor/bin/tester -p php tests

after_failure:
  # Prints *.actual files content
  - for i in $(find ./tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done
